# Generated by Django 4.2.3 on 2023-07-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cliente_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prioridad',
            field=models.CharField(),
        ),
    ]
