# Generated by Django 4.2.3 on 2023-07-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_cliente_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
