# Generated by Django 4.2.3 on 2023-07-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cliente_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion',
            field=models.CharField(),
        ),
    ]
