# Generated by Django 4.2.3 on 2023-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_cliente_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sala', models.IntegerField()),
            ],
        ),
    ]
