# Generated by Django 4.2.3 on 2023-07-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_servicio_dispobible_alter_servicio_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='dispobible',
            field=models.CharField(null=True),
        ),
    ]
