# Generated by Django 4.2.3 on 2023-07-29 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_doctor_alter_servicio_dispobible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cliente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.doctor'),
        ),
    ]
