# Generated by Django 4.2.3 on 2023-07-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_servicio_cliente_servicio_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sueldo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
