# Generated by Django 4.2.3 on 2023-07-29 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_doctor_apellido_doctor_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.doctor'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='dispobible',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], null=True),
        ),
    ]
